### ISSUE TITLE
Konten - Tali temali

### ISSUE THREAD

**Issue by mazipan** [mazipan/pramuka.online#21]
References:
- https://bukubiruku.com/tali-temali-dalam-pramuka/
- https://www.infojempol.com/2011/12/tali-temali.html?m=1
- https://www.amongguru.com/macam-macam-simpul-tali-pramuka-dilengkapi-gambar/

**Comment by muhsatrio** [comment]
Wah baru mau bikin issue ini ternyata sudah dulua dibikin. Saya boleh ngerjain gak mas? hehehehehehe kebetulan sumber referensinya sama juga nih

**Comment by andreepratama27** [comment]
Hi @mazipan,

Seems like this feature is not implemented yet (as far as I check the web), can I take over this one?

**Comment by mazipan** [comment]
Sure

**Comment by mazipan** [comment]
Closed in #89
