### ISSUE TITLE
Konten - Kompas

### ISSUE THREAD

**Issue by muhsatrio** [mazipan/pramuka.online#24]
Reference:

[https://rimbakita.com/kompas/](https://rimbakita.com/kompas/)
[https://kwarcabsumbawa.or.id/jenis-bagian-dan-fungsi-kompas/](https://kwarcabsumbawa.or.id/jenis-bagian-dan-fungsi-kompas/)
[https://id.wikipedia.org/wiki/Kompas](https://id.wikipedia.org/wiki/Kompas)

**Comment by bixamon** [comment]
izin kontribusi ke issue ini saya mas @mazipan

**Comment by rosdyana** [comment]
Apakah masih relate untuk hacktoberfest2022 @mazipan ?
